import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Container } from '@/components/Container'
import { Logo } from '@/components/SVG/logo'
import Link from 'next/link'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const LogoArea = () => (
  <div className="bg-primary text-white">
    <Container>
      <div className="flex flex-col items-center py-4 md:flex-row">
        <Link href="/">
          <Logo className="scale-75 transform md:scale-100" />
        </Link>
      </div>
    </Container>
  </div>
)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <LogoArea />
        {children}
      </body>
    </html>
  )
}
